export const productsInfo = [
  {
    id: "a",
    img: "/img/img1.jpg",
    description: "Description 1",
    isFavorite: false,
    isCart: false,
    rate: 2,
    sales: 12,
    tag: "Frete Grátis",
    price: 4.99,
    discount: 0,
  },
  {
    id: "b",
    img: "/img/img2.jpg",
    description: "Description 2",
    isFavorite: true,
    isCart: false,
    rate: 3,
    sales: 15,
    tag: "Frete Grátis 1",
    price: 6.99,
    discount: 16,
  },
  {
    id: "c",
    img: "/img/img3.jpg",
    description: "Description 3",
    isFavorite: true,
    isCart: false,
    rate: 3,
    sales: 15,
    tag: "Frete Grátis 2",
    price: 6.99,
    discount: 16,
  },
  {
    id: "d",
    img: "/img/img4.jpg",
    description: "Description 4",
    isFavorite: true,
    isCart: false,
    rate: 4,
    sales: 20,
    tag: "Frete Grátis 4",
    price: 7.99,
    discount: 12,
  },
  {
    id: "e",
    img: "/img/img5.jpg",
    description: "Description 5",
    isFavorite: true,
    isCart: true,
    rate: 5,
    sales: 600,
    tag: "Frete Grátis 5",
    price: 12.99,
    discount: 10,
  },
  {
    id: "f",
    img: "/img/img6.jpg",
    description: "Description 6",
    isFavorite: false,
    isCart: true,
    rate: 1,
    sales: 500,
    tag: "Frete Grátis 6",
    price: 22.99,
    discount: 19,
  },
  {
    id: "g",
    img: "/img/img2.jpg",
    description: "Description 7",
    isFavorite: true,
    isCart: false,
    rate: 5,
    sales: 15,
    tag: "Frete Grátis 7",
    price: 1.99,
    discount: 15,
  },
  {
    id: "h",
    img: "/img/img3.jpg",
    description: "Description 8",
    isFavorite: true,
    isCart: true,
    rate: 1,
    sales: 44,
    tag: "Frete Grátis 8",
    price: 1.99,
    discount: 15,
  },
];
